sudo: required
dist: trusty

language: python
python:
  - "3.6"

env:
  global:
    - DEPLOY_BRANCH="master"
    - DEPLOY_BASE64_KEY_VAR="JUSTDOMAINS_LISTS_DEPLOY_KEY"
    - DEPLOY_REPO_SLUG="justdomains/blocklists"
    - DEPLOY_TARGET_BRANCH="master"
    - DEPLOY_GIT_NAME="JustDomains CI"
    - DEPLOY_GIT_EMAIL="justdomains-ci"

script: 
  - python ./convertlists.py lists.json $HOME/ci/converted/ -vv
  - python ./buildrepo.py $HOME/ci/converted/ $HOME/ci/built/ --downloadbaseurl https://raw.githubusercontent.com/justdomains/blocklists/master/ -vv

deploy:
  - provider: script
    skip_cleanup: true # do not delete the built assets
    script: ci/deploy.sh $HOME/ci/built/
    on:
      branch: master

branches:
  only:
    - master
